### ISSUE TITLE
Issue with CustomQueries

### ISSUE THREAD

**Issue by leffraytheo** [SamuelAl/SQuelized-for-Processing#2]
Hey, it's me again !

I was experiencing with CustomQueries and i encountered a new issue.

Here is my code:

`import samuelal.squelized.*;

SQLConnection connection;
Table table;

void setup() {

  connection = new MySQLConnection("root", "", "jdbc:mysql://localhost:3306/archibase?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC");
  table = connection.getTable("personnes");
  printTable(table);
  
  String query = "INSERT INTO personnes VALUES(3, 'Smith', 'John');";
  Table testTable = connection.runQuery(query);
  printTable(testTable);
}

void printTable(Table table) {

  for (TableRow row : table.rows())
  {
    for (int i = 0; i < row.getColumnCount(); i++)
    {
      System.out.print(row.getString(i) + "  ");
    }
    System.out.println();
  }
}`

and here is the issue:

`SQuelized 1.0.0 by Samuel Alarco Cantos https://samuelal.github.io/squelized.github.io/index.html
Connected as to jdbc:mysql://localhost:3306/archibase?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
1  me  me  
2  Mercury  Freddie  
Connection failed
Can not issue data manipulation statements with executeQuery().
`

I know that i can use insetIntoColumns to achieve what i cant, but i know that i will need CustomQueries in my future project, so i would like to know what i did wrong to have this issue.

Thank you in advance !

**Comment by SamuelAl** [comment]
Hello again!
Thanks for pointing out this issue. I am afraid that at the moment the insertIntoColumns function is the only way to access insert update functionality. However, we are working hard to implement support for custom update queries such as insert queries in our future release, and they will be run as you are intending. If everything goes well according to timeline, the new release should be ready by end of next week. I will notify you when the update is ready.
This is a very young project, so your experience is very valuable to us and any feature suggestion to improve the project is very welcomed. We promise to do our best to implement these features in future releases. 
Thank you!

**Comment by leffraytheo** [comment]
Thank you for your answer, i understand that it's a young project. I'm happy to take part in the experience of this project and his feedback. 
What are the SQL functions that i can use whit the custom query system ?
I can't wait for the new release, have a nice day !

**Comment by deleojur** [comment]
How is version 1.1 coming along?
insertIntoColumns appears to be having the same problem, at least for the mySQL connection.

**Comment by SamuelAl** [comment]
Hi @deleojur and @leffraytheo !
Sorry for the delay in the new release. Have been really busy with work lately and there were some delays. We have just made a new release for v1.1, which includes a new method updateQuery to support custom Update Queries and solve some bugs with insertIntoColumns for some SQL servers. This is a partial release, as we are planning to expand our Update query functionality with some premade query functions, but with this users should be able to run their custom update queries. 
You can download the new release straight from GitHub, as Processing will probably take some days to detect the new release and update accordingly. We look forward to your feedback, which as always is super important to detect new bugs and add new features!
Thank you so much for your patience and your continued support.

**Comment by SamuelAl** [comment]
Will be updating the website in the coming days to add documentation and links to the new release from the website

**Comment by deleojur** [comment]
Hi @SamuelAl thanks for taking the time to look into this issue! 
What's the easiest way to get a new export into Processing from the Github repository?
I was able to get the project into Eclipse and run an export from there; is there another, more direct way? :)

EDIT: found it -> distribution\SQuelized-2\download\SQuelized and overwrite the original library into the library folder of Processing.
Thanks for being involved, will create a list of feedback. 

One thing that is apparent, but I guess it's a JDBC issue, is that aliasses don't appear to work very well. Will get to the bottom of it. It only happens when a result returns two tables who share a columnname (for example in a JOIN statement).

**Comment by leffraytheo** [comment]
Hi,

thank you very much, ill look for the changes !

**Comment by SamuelAl** [comment]
Hi guys, if its all fine with you guys I will close this issue. You can always open new issues if you find other bugs or would like to include new features. This will help to keep the issues and feedback organized. Thank you all!
